# Generated by Django 4.1.2 on 2022-11-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ManyToManyField(blank=True, to='auctions.category'),
        ),
    ]
