# Generated by Django 4.1.2 on 2022-11-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='bid',
        ),
    ]
